import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'README',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Authoring',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'authoring'}],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developer-guide'}],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;
